### ISSUE TITLE
unexpected EOF while looking for matching `"'

### ISSUE THREAD

**Issue by bobcao3** [AOSC-Dev/abbs-meta#2]
python3 abbsmeta.py abbs.db /lib/abbs/repo/
...
2016-10-10 08:45:43,216 W /lib/abbs/repo/base-devel/autobuild3/autobuild/defines: bash: line 34: abwarn: command not found
...
2016-10-10 08:45:56,570 I extra-doc/a2ps
2016-10-10 08:45:56,584 W /lib/abbs/repo/extra-doc/a2ps/spec: bash: line 8: unexpected EOF while looking for matching `"'
bash: line 9: syntax error: unexpected end of file
Traceback (most recent call last):
  File "abbsmeta.py", line 132, in <module>
    sys.exit(main(*sys.argv[1:]))
  File "abbsmeta.py", line 127, in main
    scan_abbs_tree(cur, path)
  File "abbsmeta.py", line 92, in scan_abbs_tree
    spec = read_bash_vars(os.path.join(fullpath, 'spec'))
  File "abbsmeta.py", line 76, in read_bash_vars
    assert len(var) == len(lines)
AssertionError

**Comment by bobcao3** [comment]
After pulling the master repo, problem dissappeared

**Comment by gumblex** [comment]
Fixed in https://github.com/AOSC-Dev/aosc-os-abbs/commit/7c50c736331817ceb284c57fd81c699b319852dc
